/**
 * 错误码总表（`contracts/admin-api.md` §0.4）与 HTTP 状态码映射。
 *
 * 原则七：错误码 MUST 全局唯一且语义稳定，MUST NOT 出现同码不同义。
 * 本表**复用**运行环境既有码（`VALIDATION_FAILED` / `NOT_FOUND` / `INTERNAL_ERROR` /
 * `SERVICE_UNAVAILABLE`），并新增 `ADM_` 前缀码——前缀保证与既有码表零碰撞，
 * 同时可一眼区分来源。
 *
 * 该模块是**跨层共享内核**：`routes/`、`domain/`、`infra/` 均可引用
 * （与 `agent-backend/src/types.ts` 的角色相同），因此不构成越级依赖。
 */

/** 全部错误码常量（与契约 §0.4 逐行对应） */
export const ERROR_CODES = {
  // ---- 复用既有码 ----
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  // ---- 数字人（§5、§7）----
  ADM_AGENT_NAME_TAKEN: 'ADM_AGENT_NAME_TAKEN',
  ADM_AGENT_IN_USE: 'ADM_AGENT_IN_USE',
  ADM_AGENT_INVALID_REF: 'ADM_AGENT_INVALID_REF',
  ADM_AGENT_NOT_FOUND: 'ADM_AGENT_NOT_FOUND',
  // ---- SKILL（§4）----
  ADM_SKILL_NAME_TAKEN: 'ADM_SKILL_NAME_TAKEN',
  ADM_SKILL_ARCHIVE_INVALID: 'ADM_SKILL_ARCHIVE_INVALID',
  ADM_SKILL_ARCHIVE_UNSAFE: 'ADM_SKILL_ARCHIVE_UNSAFE',
  ADM_SKILL_NOT_FOUND: 'ADM_SKILL_NOT_FOUND',
  // ---- MCP 服务（§3）----
  ADM_MCP_SERVICE_NOT_FOUND: 'ADM_MCP_SERVICE_NOT_FOUND',
  ADM_MCP_SERVICE_UNMANAGED: 'ADM_MCP_SERVICE_UNMANAGED',
  // ---- 部署与运行形态（§6、§1）----
  ADM_RUNTIME_FORM_NOT_CONFIGURED: 'ADM_RUNTIME_FORM_NOT_CONFIGURED',
  ADM_DEPLOY_VALIDATION_FAILED: 'ADM_DEPLOY_VALIDATION_FAILED',
  ADM_DEPLOY_TARGET_NOT_WRITABLE: 'ADM_DEPLOY_TARGET_NOT_WRITABLE',
  // ---- 用户（§6）----
  ADM_USER_ID_TAKEN: 'ADM_USER_ID_TAKEN',
  ADM_USER_NOT_FOUND: 'ADM_USER_NOT_FOUND',
  // ---- 通用 ----
  ADM_CONFIG_REVISION_CONFLICT: 'ADM_CONFIG_REVISION_CONFLICT',
  ADM_DOCKER_UNAVAILABLE: 'ADM_DOCKER_UNAVAILABLE',
  ADM_COMPOSE_FILE_UNREADABLE: 'ADM_COMPOSE_FILE_UNREADABLE',
  ADM_STORAGE_UNAVAILABLE: 'ADM_STORAGE_UNAVAILABLE',
  ADM_RUNTIME_UNREACHABLE: 'ADM_RUNTIME_UNREACHABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/**
 * 错误码 → HTTP 状态码（契约 §0.4 的 HTTP 列）。
 *
 * 未登记的码由 `api-error.ts` 回退为 500，避免出现"未知码配错状态码"。
 */
export const ERROR_STATUS: Readonly<Record<string, number>> = {
  [ERROR_CODES.VALIDATION_FAILED]: 400,
  [ERROR_CODES.NOT_FOUND]: 404,
  [ERROR_CODES.INTERNAL_ERROR]: 500,
  [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,

  [ERROR_CODES.ADM_AGENT_NAME_TAKEN]: 409,
  [ERROR_CODES.ADM_AGENT_IN_USE]: 409,
  [ERROR_CODES.ADM_AGENT_INVALID_REF]: 400,
  [ERROR_CODES.ADM_AGENT_NOT_FOUND]: 404,

  [ERROR_CODES.ADM_SKILL_NAME_TAKEN]: 409,
  [ERROR_CODES.ADM_SKILL_ARCHIVE_INVALID]: 400,
  [ERROR_CODES.ADM_SKILL_ARCHIVE_UNSAFE]: 400,
  [ERROR_CODES.ADM_SKILL_NOT_FOUND]: 404,

  [ERROR_CODES.ADM_MCP_SERVICE_NOT_FOUND]: 404,
  [ERROR_CODES.ADM_MCP_SERVICE_UNMANAGED]: 409,
  [ERROR_CODES.ADM_RUNTIME_FORM_NOT_CONFIGURED]: 409,
  [ERROR_CODES.ADM_DEPLOY_VALIDATION_FAILED]: 409,
  [ERROR_CODES.ADM_DEPLOY_TARGET_NOT_WRITABLE]: 409,

  [ERROR_CODES.ADM_USER_ID_TAKEN]: 409,
  [ERROR_CODES.ADM_USER_NOT_FOUND]: 404,
  [ERROR_CODES.ADM_CONFIG_REVISION_CONFLICT]: 409,

  [ERROR_CODES.ADM_DOCKER_UNAVAILABLE]: 503,
  [ERROR_CODES.ADM_COMPOSE_FILE_UNREADABLE]: 503,
  [ERROR_CODES.ADM_STORAGE_UNAVAILABLE]: 503,
  [ERROR_CODES.ADM_RUNTIME_UNREACHABLE]: 503,
};

/** 全部错误码清单（T120 的机械核对与测试共用） */
export const ALL_ERROR_CODES: readonly string[] = Object.values(ERROR_CODES);

/** 平台操作者标识（`research.md` D11）；仅用于审计字段，不参与 users/ 目录划分 */
export const PLATFORM_OPERATOR = 'zyw_admin';
